export const ROOMS = [
  {
    id: 1,
    title: "Presidential Suite",
    description: "Experience the pinnacle of luxury with panoramic ocean views and private butler service.",
    price: "৳120,000 BDT",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=2070&auto=format&fit=crop",
    features: ["Private Terrace", "Jacuzzi", "24/7 Butler", "Mini Bar"],
  },
  {
    id: 2,
    title: "Luxury Ocean Villa",
    description: "A secluded sanctuary featuring a private infinity pool and direct beach access.",
    price: "৳85,000 BDT",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=1780&auto=format&fit=crop",
    features: ["Infinity Pool", "Garden Shower", "Sound System", "Wine Cellar"],
  },
  {
    id: 3,
    title: "Executive Royal Room",
    description: "Contemporary elegence meets comfort, perfect for business or leisure stays.",
    price: "৳45,000 BDT",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?q=80&w=2070&auto=format&fit=crop",
    features: ["King Bed", "Work Station", "Smart Room Controls", "Premium Bath"],
  },
  {
    id: 4,
    title: "Family Sunrise Suite",
    description: "Spacious and bright suite designed for the ultimate family vacation experience.",
    price: "৳60,000 BDT",
    image: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?q=80&w=2074&auto=format&fit=crop",
    features: ["2 Bedrooms", "Kitchenette", "Kids Area", "Balcony"],
  },
  {
    id: 5,
    title: "Honeymoon Penthouse",
    description: "An intimate and romantic getaway with 360-degree views of the resort skyline.",
    price: "৳95,000 BDT",
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?q=80&w=1974&auto=format&fit=crop",
    features: ["Sunken Bath", "Champagne Service", "Private Lift", "Sky Garden"],
  },
  {
    id: 6,
    title: "Garden Deluxe Room",
    description: "Tranquil room surrounded by lush tropical gardens for a peaceful retreat.",
    price: "৳35,000 BDT",
    image: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?q=80&w=2070&auto=format&fit=crop",
    features: ["Garden View", "Outdoor Seating", "Eco-friendly", "Rain Shower"],
  },
];

export const DINING_RESTAURANTS = [
  {
    id: 1,
    name: "Olive",
    cuisine: "Mediterranean",
    tagline: "A taste of the Mediterranean, refined.",
    description:
      "Experience the flavors of the Mediterranean coastline in an intimate, rustic-elegant setting. Our award-winning chefs craft each dish with locally sourced ingredients, seasonal produce, and time-honored recipes passed down through generations.",
    image: "/assets/dining/olive.jpg",
    hours: "6:00 PM – 11:00 PM",
    priceRange: "৳৳৳",
    dressCode: "Smart Casual",
    signatures: ["Truffle Risotto", "Grilled Lamb Rack", "Tiramisu al Limone"],
    ambiance: ["Candlelit", "Romantic", "Live Acoustic"],
  },
  {
    id: 2,
    name: "Rebulation",
    cuisine: "Modern Fusion",
    tagline: "Where culinary boundaries dissolve.",
    description:
      "A bold, contemporary dining experience featuring an open kitchen where our chefs push the boundaries of flavor. Rebulation fuses global techniques with premium ingredients, creating dishes that are as visually stunning as they are delicious.",
    image: "/assets/dining/revolution.jpg",
    hours: "12:00 PM – 11:30 PM",
    priceRange: "৳৳৳৳",
    dressCode: "Smart Elegant",
    signatures: ["Wagyu Tataki", "Deconstructed Ceviche", "Miso-Glazed Black Cod"],
    ambiance: ["Chef's Counter", "Industrial Chic", "Open Kitchen"],
  },
  {
    id: 3,
    name: "Arabian Lounge",
    cuisine: "Middle Eastern",
    tagline: "An oasis of flavor and opulence.",
    description:
      "Step into a world of Arabian grandeur. The Arabian Lounge offers an immersive dining experience with authentic Middle Eastern cuisine, aromatic spices, and traditional shisha in a setting adorned with hand-crafted Moroccan tiles and plush velvet seating.",
    image: "/assets/dining/arabian-lounge.jpg",
    hours: "4:00 PM – 1:00 AM",
    priceRange: "৳৳৳",
    dressCode: "Resort Casual",
    signatures: ["Mixed Mezze Platter", "Lamb Ouzi", "Kunafa"],
    ambiance: ["Ornate", "Lounge Seating", "Shisha Garden"],
  },
  {
    id: 4,
    name: "Lostalgia",
    cuisine: "Vintage Comfort",
    tagline: "Where memories meet the menu.",
    description:
      "A heartwarming retreat into the past. Lostalgia blends nostalgic comfort food with artisanal craft cocktails in a beautifully restored vintage interior. Every corner tells a story, from the antique decor to the carefully curated vinyl soundtrack.",
    image: "/assets/dining/lostalgia.jpg",
    hours: "11:00 AM – 12:00 AM",
    priceRange: "৳৳",
    dressCode: "Casual",
    signatures: ["Smoked BBQ Ribs", "Truffle Mac & Cheese", "Classic Old Fashioned"],
    ambiance: ["Retro Decor", "Vinyl Music", "Craft Cocktails"],
  },
  {
    id: 5,
    name: "Saigon",
    cuisine: "Vietnamese",
    tagline: "The soul of Vietnam, elevated.",
    description:
      "Journey through the vibrant streets of Ho Chi Minh City without leaving the resort. Saigon presents authentic Vietnamese cuisine with a contemporary twist, set within a lush, zen-inspired space of bamboo, paper lanterns, and flowing water features.",
    image: "/assets/dining/saigon.jpg",
    hours: "11:30 AM – 10:30 PM",
    priceRange: "৳৳",
    dressCode: "Casual",
    signatures: ["Phở Bò", "Bánh Mì Wagyu", "Vietnamese Coffee Crème Brûlée"],
    ambiance: ["Zen Garden", "Paper Lanterns", "Indoor Plants"],
  },
];

export const EVENT_VENUES = [
  {
    id: 1,
    name: "Banquet Hall",
    category: "Indoor Grandeur",
    tagline: "Where grand celebrations come to life.",
    description: "Our majestic Banquet Hall offers a sophisticated venue for weddings, galas, and large-scale celebrations. With soaring ceilings, crystal chandeliers, and customizable configurations, it provides the perfect backdrop for your most memorable moments.",
    image: "/assets/events/banquet-hall.jpg",
    capacity: "Up to 500 Guests",
    features: ["Grand Entrance", "Professional Lighting", "Customizable Decor", "VIP Suite"],
  },
  {
    id: 2,
    name: "Meeting Rooms",
    category: "Corporate Excellence",
    tagline: "Inspiring productivity in style.",
    description: "Designated for the modern professional, our high-tech Meeting Rooms are equipped with state-of-the-art audiovisual technology and comfortable ergonomic seating. Ideal for board meetings, workshops, and intimate corporate gatherings.",
    image: "/assets/events/meeting-rooms.jpg",
    capacity: "10 - 50 Guests",
    features: ["Smart Displays", "Video Conferencing", "High-speed Wi-Fi", "Catering Access"],
  },
  {
    id: 3,
    name: "Amphitheater",
    category: "Artistic Open-Air",
    tagline: "Performances under the stars.",
    description: "Our stunning open-air Amphitheater is a unique venue for cultural performances, live music, and outdoor presentations. Surrounded by lush greenery, it offers an immersive acoustic environment and a magical atmosphere for any evening event.",
    image: "/assets/events/amphitheater.jpg",
    capacity: "Up to 300 Guests",
    features: ["Natural Acoustics", "Stage Lighting", "Tiered Seating", "Scenic Backdrop"],
  },
  {
    id: 4,
    name: "Fountain View Lawn",
    category: "Nature's Elegance",
    tagline: "Serene beauty for your special day.",
    description: "A meticulously manicured lawn offering breathtaking views of our iconic fountains. This versatile outdoor space is perfect for romantic garden weddings, cocktail receptions, and elegant afternoon tea parties in the gentle breeze.",
    image: "/assets/events/fountain-view.jpg",
    capacity: "Up to 200 Guests",
    features: ["Panoramic Fountain Views", "Manicured Gardens", "Ambient Lighting", "Tenting Options"],
  },
  {
    id: 5,
    name: "Plan Your Own Event",
    category: "Custom Creations",
    tagline: "Your vision, our expertise.",
    description: "Have a unique idea? Our dedicated events team is here to help you design a bespoke experience tailored to your specific needs. From intimate surprises to large-scale themed parties, we bring your vision to life with precision and flair.",
    image: "/assets/events/own-event.jpg",
    capacity: "Flexible",
    features: ["Dedicated Event Planner", "Custom Menu Design", "Tailored Decor", "Professional Staffing"],
  },
];
